/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(main)': RouteRecordInfo<'/(main)', '/', Record<never, never>, Record<never, never>, '/(main)/account' | '/(main)/account/profile' | '/(main)/account/settings' | '/(main)/admin/publications/' | '/(main)/publication' | 'Dashboard' | 'VerifyEmail' | 'admin:users' | 'admin:users:details' | 'feed' | 'publication:' | 'publication:createSubmission' | 'publication:home' | 'publication:index' | 'publication:setup' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup:users' | 'reviews' | 'submission:content' | 'submission:details' | 'submission:draft' | 'submission:export' | 'submission:metaForm' | 'submission:preview' | 'submission:review' | 'submission:view' | 'submissions'>,
    '/(main)/account': RouteRecordInfo<'/(main)/account', '/account', Record<never, never>, Record<never, never>, '/(main)/account/profile' | '/(main)/account/settings'>,
    '/(main)/account/profile': RouteRecordInfo<'/(main)/account/profile', '/account/profile', Record<never, never>, Record<never, never>>,
    '/(main)/account/settings': RouteRecordInfo<'/(main)/account/settings', '/account/settings', Record<never, never>, Record<never, never>>,
    '/(main)/admin/publications/': RouteRecordInfo<'/(main)/admin/publications/', '/admin/publications', Record<never, never>, Record<never, never>>,
    'admin:users': RouteRecordInfo<'admin:users', '/admin/users', Record<never, never>, Record<never, never>>,
    'admin:users:details': RouteRecordInfo<'admin:users:details', '/admin/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'Dashboard': RouteRecordInfo<'Dashboard', '/dashboard', Record<never, never>, Record<never, never>>,
    'feed': RouteRecordInfo<'feed', '/feed', Record<never, never>, Record<never, never>>,
    '/(main)/publication': RouteRecordInfo<'/(main)/publication', '/publication', Record<never, never>, Record<never, never>, 'publication:' | 'publication:createSubmission' | 'publication:home' | 'publication:index' | 'publication:setup' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup:users'>,
    'publication:index': RouteRecordInfo<'publication:index', '/publication', Record<never, never>, Record<never, never>>,
    'publication:': RouteRecordInfo<'publication:', '/publication/:id', { id: ParamValue<true> }, { id: ParamValue<false> }, 'publication:createSubmission' | 'publication:home' | 'publication:setup' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup:users'>,
    'publication:home': RouteRecordInfo<'publication:home', '/publication/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:createSubmission': RouteRecordInfo<'publication:createSubmission', '/publication/:id/create', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:setup': RouteRecordInfo<'publication:setup', '/publication/:id/setup', { id: ParamValue<true> }, { id: ParamValue<false> }, 'publication:setup:basic' | 'publication:setup:content' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup:users'>,
    'publication:setup:basic': RouteRecordInfo<'publication:setup:basic', '/publication/:id/setup/basic', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:setup:content': RouteRecordInfo<'publication:setup:content', '/publication/:id/setup/content', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:setup:criteria': RouteRecordInfo<'publication:setup:criteria', '/publication/:id/setup/criteria', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:setup:metaForms': RouteRecordInfo<'publication:setup:metaForms', '/publication/:id/setup/metaform', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'publication:setup:users': RouteRecordInfo<'publication:setup:users', '/publication/:id/setup/users', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'reviews': RouteRecordInfo<'reviews', '/reviews', Record<never, never>, Record<never, never>>,
    'submission:content': RouteRecordInfo<'submission:content', '/submission/:id/content', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:details': RouteRecordInfo<'submission:details', '/submission/:id/details', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:draft': RouteRecordInfo<'submission:draft', '/submission/:id/draft', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:export': RouteRecordInfo<'submission:export', '/submission/:id/export', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:metaForm': RouteRecordInfo<'submission:metaForm', '/submission/:id/meta-form/:formId', { id: ParamValue<true>, formId: ParamValue<true> }, { id: ParamValue<false>, formId: ParamValue<false> }>,
    'submission:preview': RouteRecordInfo<'submission:preview', '/submission/:id/preview', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:review': RouteRecordInfo<'submission:review', '/submission/:id/review', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submission:view': RouteRecordInfo<'submission:view', '/submission/:id/view', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'submissions': RouteRecordInfo<'submissions', '/submissions', Record<never, never>, Record<never, never>>,
    'VerifyEmail': RouteRecordInfo<'VerifyEmail', '/verify-email/:expires/:token', { expires: ParamValue<true>, token: ParamValue<true> }, { expires: ParamValue<false>, token: ParamValue<false> }>,
    '/(public)': RouteRecordInfo<'/(public)', '/', Record<never, never>, Record<never, never>, '/(public)/auth.redirect.google' | '/(public)/auth.redirect.orcid' | '/(public)/logout' | 'RequestPasswordReset' | 'ResetPassword' | 'acceptInvite' | 'index' | 'login' | 'register'>,
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    'acceptInvite': RouteRecordInfo<'acceptInvite', '/accept-invite/:invite(.*)', { invite: ParamValue<true> }, { invite: ParamValue<false> }>,
    '/(public)/auth.redirect.google': RouteRecordInfo<'/(public)/auth.redirect.google', '/auth/redirect/google', Record<never, never>, Record<never, never>>,
    '/(public)/auth.redirect.orcid': RouteRecordInfo<'/(public)/auth.redirect.orcid', '/auth/redirect/orcid', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    '/(public)/logout': RouteRecordInfo<'/(public)/logout', '/logout', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'RequestPasswordReset': RouteRecordInfo<'RequestPasswordReset', '/request-password-reset', Record<never, never>, Record<never, never>>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'error403': RouteRecordInfo<'error403', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    'error403': RouteRecordInfo<'error403', '/Error403', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(main).vue': {
      routes: '/(main)' | 'publication:home' | 'publication:index' | '/(main)/admin/publications/' | 'admin:users' | 'publication:' | 'admin:users:details' | '/(main)/submission/[id]' | '/(main)/account' | '/(main)/admin' | 'publication:setup:basic' | 'publication:setup:content' | 'submission:content' | 'publication:createSubmission' | 'publication:setup:criteria' | 'Dashboard' | 'submission:details' | 'submission:draft' | 'submission:export' | 'feed' | 'submission:metaForm' | 'publication:setup:metaForms' | 'submission:preview' | '/(main)/account/profile' | '/(main)/publication' | '/(main)/admin/publications' | 'submission:review' | 'reviews' | '/(main)/account/settings' | 'publication:setup' | '/(main)/submission' | 'submissions' | 'publication:setup:users' | '/(main)/admin/users' | 'VerifyEmail' | 'submission:view'
      views: 'default'
    }
    'src/pages/(main)/account.vue': {
      routes: '/(main)/account' | '/(main)/account/profile' | '/(main)/account/settings'
      views: 'default'
    }
    'src/pages/(main)/account/profile.vue': {
      routes: '/(main)/account/profile'
      views: never
    }
    'src/pages/(main)/account/settings.vue': {
      routes: '/(main)/account/settings'
      views: never
    }
    'src/pages/(main)/admin/publications/index.vue': {
      routes: '/(main)/admin/publications/'
      views: never
    }
    'src/pages/(main)/admin/users/index.vue': {
      routes: 'admin:users'
      views: never
    }
    'src/pages/(main)/admin/users/[id].vue': {
      routes: 'admin:users:details'
      views: never
    }
    'src/pages/(main)/dashboard.vue': {
      routes: 'Dashboard'
      views: never
    }
    'src/pages/(main)/feed.vue': {
      routes: 'feed'
      views: never
    }
    'src/pages/(main)/publication.vue': {
      routes: '/(main)/publication' | 'publication:home' | 'publication:index' | 'publication:' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:createSubmission' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup' | 'publication:setup:users'
      views: 'default'
    }
    'src/pages/(main)/publication/index.vue': {
      routes: 'publication:index'
      views: never
    }
    'src/pages/(main)/publication/[id].vue': {
      routes: 'publication:' | 'publication:home' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:createSubmission' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup' | 'publication:setup:users'
      views: 'default'
    }
    'src/pages/(main)/publication/[id]/index.vue': {
      routes: 'publication:home'
      views: never
    }
    'src/pages/(main)/publication/[id]/create.vue': {
      routes: 'publication:createSubmission'
      views: never
    }
    'src/pages/(main)/publication/[id]/setup.vue': {
      routes: 'publication:setup' | 'publication:setup:basic' | 'publication:setup:content' | 'publication:setup:criteria' | 'publication:setup:metaForms' | 'publication:setup:users'
      views: 'default'
    }
    'src/pages/(main)/publication/[id]/setup/basic.vue': {
      routes: 'publication:setup:basic'
      views: never
    }
    'src/pages/(main)/publication/[id]/setup/content.vue': {
      routes: 'publication:setup:content'
      views: never
    }
    'src/pages/(main)/publication/[id]/setup/criteria.vue': {
      routes: 'publication:setup:criteria'
      views: never
    }
    'src/pages/(main)/publication/[id]/setup/metaform.vue': {
      routes: 'publication:setup:metaForms'
      views: never
    }
    'src/pages/(main)/publication/[id]/setup/users.vue': {
      routes: 'publication:setup:users'
      views: never
    }
    'src/pages/(main)/reviews.vue': {
      routes: 'reviews'
      views: never
    }
    'src/pages/(main)/submission/[id]/content.vue': {
      routes: 'submission:content'
      views: never
    }
    'src/pages/(main)/submission/[id]/details.vue': {
      routes: 'submission:details'
      views: never
    }
    'src/pages/(main)/submission/[id]/draft.vue': {
      routes: 'submission:draft'
      views: never
    }
    'src/pages/(main)/submission/[id]/export.vue': {
      routes: 'submission:export'
      views: never
    }
    'src/pages/(main)/submission/[id]/meta-form.[formId].vue': {
      routes: 'submission:metaForm'
      views: never
    }
    'src/pages/(main)/submission/[id]/preview.vue': {
      routes: 'submission:preview'
      views: never
    }
    'src/pages/(main)/submission/[id]/review.vue': {
      routes: 'submission:review'
      views: never
    }
    'src/pages/(main)/submission/[id]/view.vue': {
      routes: 'submission:view'
      views: never
    }
    'src/pages/(main)/submissions.vue': {
      routes: 'submissions'
      views: never
    }
    'src/pages/(main)/verify-email.[expires].[token].vue': {
      routes: 'VerifyEmail'
      views: never
    }
    'src/pages/(public).vue': {
      routes: '/(public)' | 'index' | 'acceptInvite' | '/(public)/auth.redirect.google' | '/(public)/auth.redirect.orcid' | 'login' | '/(public)/logout' | 'register' | 'RequestPasswordReset' | 'ResetPassword'
      views: 'default'
    }
    'src/pages/(public)/index.vue': {
      routes: 'index'
      views: never
    }
    'src/pages/(public)/accept-invite.[...invite].vue': {
      routes: 'acceptInvite'
      views: never
    }
    'src/pages/(public)/auth.redirect.google.vue': {
      routes: '/(public)/auth.redirect.google'
      views: never
    }
    'src/pages/(public)/auth.redirect.orcid.vue': {
      routes: '/(public)/auth.redirect.orcid'
      views: never
    }
    'src/pages/(public)/login.vue': {
      routes: 'login'
      views: never
    }
    'src/pages/(public)/logout.vue': {
      routes: '/(public)/logout'
      views: never
    }
    'src/pages/(public)/register.vue': {
      routes: 'register'
      views: never
    }
    'src/pages/(public)/request-password-reset.vue': {
      routes: 'RequestPasswordReset'
      views: never
    }
    'src/pages/(public)/reset-password.[token].vue': {
      routes: 'ResetPassword'
      views: never
    }
    'src/pages/[...path].vue': {
      routes: 'error403'
      views: never
    }
    'src/pages/Error403.vue': {
      routes: 'error403'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
