FROM busybox:1
COPY buildstamp buildstamp
RUN --mount=type=cache,target=/tmp/output \
    mkdir -p /var/output-cache/ \
    && cp -p -R /tmp/output/. /var/.output-cache/
    && rm -rf /tmp/output/* || true
