/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | 'admin:dashboard'
      | 'admin:publication:index'
      | 'admin:user:id'
      | 'admin:users'
      | 'user_details'
      | 'user_details:submissions'
    >,
    'admin:dashboard': RouteRecordInfo<
      'admin:dashboard',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin:publication:index': RouteRecordInfo<
      'admin:publication:index',
      '/admin/publications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin:user:id': RouteRecordInfo<
      'admin:user:id',
      '/admin/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'user_details'
      | 'user_details:submissions'
    >,
    'user_details': RouteRecordInfo<
      'user_details',
      '/admin/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'user_details:submissions': RouteRecordInfo<
      'user_details:submissions',
      '/admin/user/:id/submissions',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin:users': RouteRecordInfo<
      'admin:users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'manage:index': RouteRecordInfo<
      'manage:index',
      '/manage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/manage/publication': RouteRecordInfo<
      '/manage/publication',
      '/manage/publication',
      Record<never, never>,
      Record<never, never>,
      | '/manage/publication/[id]/'
      | '/manage/publication/[id]/(tabs)'
      | '/manage/publication/[id]/dashboard/'
      | 'manage:publication:dashboard'
      | 'manage:publication:id'
      | 'manage:publication:invited'
      | 'manage:publication:submissions'
      | 'manage:publication:submitter'
      | 'manage:publication:submitters'
      | 'manage:publication:team'
      | 'manage:publication:team_member'
    >,
    'manage:publication:id': RouteRecordInfo<
      'manage:publication:id',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/manage/publication/[id]/'
      | '/manage/publication/[id]/(tabs)'
      | '/manage/publication/[id]/dashboard/'
      | 'manage:publication:dashboard'
      | 'manage:publication:invited'
      | 'manage:publication:submissions'
      | 'manage:publication:submitter'
      | 'manage:publication:submitters'
      | 'manage:publication:team'
      | 'manage:publication:team_member'
    >,
    '/manage/publication/[id]/(tabs)': RouteRecordInfo<
      '/manage/publication/[id]/(tabs)',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'manage:publication:invited'
      | 'manage:publication:team'
    >,
    'manage:publication:invited': RouteRecordInfo<
      'manage:publication:invited',
      '/manage/publication/:id/invited',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:team': RouteRecordInfo<
      'manage:publication:team',
      '/manage/publication/:id/team',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/manage/publication/[id]/': RouteRecordInfo<
      '/manage/publication/[id]/',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:dashboard': RouteRecordInfo<
      'manage:publication:dashboard',
      '/manage/publication/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/manage/publication/[id]/dashboard/'
      | 'manage:publication:submissions'
      | 'manage:publication:submitters'
    >,
    '/manage/publication/[id]/dashboard/': RouteRecordInfo<
      '/manage/publication/[id]/dashboard/',
      '/manage/publication/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:submissions': RouteRecordInfo<
      'manage:publication:submissions',
      '/manage/publication/:id/dashboard/submissions',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:submitters': RouteRecordInfo<
      'manage:publication:submitters',
      '/manage/publication/:id/dashboard/submitters',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:submitter': RouteRecordInfo<
      'manage:publication:submitter',
      '/manage/publication/:id/submitters/:userId',
      { id: ParamValue<true>, userId: ParamValue<true> },
      { id: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
    'manage:publication:team_member': RouteRecordInfo<
      'manage:publication:team_member',
      '/manage/publication/:id/team/:userId',
      { id: ParamValue<true>, userId: ParamValue<true> },
      { id: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/admin.vue': {
      routes:
        | '/admin'
        | 'admin:dashboard'
        | 'admin:publication:index'
        | 'admin:user:id'
        | 'admin:users'
        | 'user_details'
        | 'user_details:submissions'
      views:
        | 'default'
    }
    'src/routes/admin/index.vue': {
      routes:
        | 'admin:dashboard'
      views:
        | never
    }
    'src/routes/admin/publications.vue': {
      routes:
        | 'admin:publication:index'
      views:
        | never
    }
    'src/routes/admin/user/[id].vue': {
      routes:
        | 'admin:user:id'
        | 'user_details'
        | 'user_details:submissions'
      views:
        | 'default'
    }
    'src/routes/admin/user/[id]/index.vue': {
      routes:
        | 'user_details'
      views:
        | never
    }
    'src/routes/admin/user/[id]/submissions.vue': {
      routes:
        | 'user_details:submissions'
      views:
        | never
    }
    'src/routes/admin/users.vue': {
      routes:
        | 'admin:users'
      views:
        | never
    }
    'src/routes/manage/index.vue': {
      routes:
        | 'manage:index'
      views:
        | never
    }
    'src/routes/manage/publication.vue': {
      routes:
        | '/manage/publication'
        | '/manage/publication/[id]/'
        | '/manage/publication/[id]/(tabs)'
        | '/manage/publication/[id]/dashboard/'
        | 'manage:publication:dashboard'
        | 'manage:publication:id'
        | 'manage:publication:invited'
        | 'manage:publication:submissions'
        | 'manage:publication:submitter'
        | 'manage:publication:submitters'
        | 'manage:publication:team'
        | 'manage:publication:team_member'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id].vue': {
      routes:
        | '/manage/publication/[id]/'
        | '/manage/publication/[id]/(tabs)'
        | '/manage/publication/[id]/dashboard/'
        | 'manage:publication:dashboard'
        | 'manage:publication:id'
        | 'manage:publication:invited'
        | 'manage:publication:submissions'
        | 'manage:publication:submitter'
        | 'manage:publication:submitters'
        | 'manage:publication:team'
        | 'manage:publication:team_member'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id]/(tabs).vue': {
      routes:
        | '/manage/publication/[id]/(tabs)'
        | 'manage:publication:invited'
        | 'manage:publication:team'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id]/(tabs)/invited.vue': {
      routes:
        | 'manage:publication:invited'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/(tabs)/team.vue': {
      routes:
        | 'manage:publication:team'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/index.vue': {
      routes:
        | '/manage/publication/[id]/'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/dashboard.vue': {
      routes:
        | '/manage/publication/[id]/dashboard/'
        | 'manage:publication:dashboard'
        | 'manage:publication:submissions'
        | 'manage:publication:submitters'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id]/dashboard/index.vue': {
      routes:
        | '/manage/publication/[id]/dashboard/'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/dashboard/submissions.vue': {
      routes:
        | 'manage:publication:submissions'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/dashboard/submitters.vue': {
      routes:
        | 'manage:publication:submitters'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/submitters/[userId].vue': {
      routes:
        | 'manage:publication:submitter'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/team/[userId].vue': {
      routes:
        | 'manage:publication:team_member'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
