/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'account': RouteRecordInfo<
      'account',
      '/account',
      Record<never, never>,
      Record<never, never>,
      | 'account:labs'
      | 'account:labs:record-of-review'
      | 'account:profile'
      | 'account:record_of_review'
      | 'account:settings'
    >,
    'account:labs': RouteRecordInfo<
      'account:labs',
      '/account/labs',
      Record<never, never>,
      Record<never, never>,
      | 'account:labs:record-of-review'
    >,
    'account:labs:record-of-review': RouteRecordInfo<
      'account:labs:record-of-review',
      '/account/labs/record-of-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account:profile': RouteRecordInfo<
      'account:profile',
      '/account/profile',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account:record_of_review': RouteRecordInfo<
      'account:record_of_review',
      '/account/record-of-review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'account:settings': RouteRecordInfo<
      'account:settings',
      '/account/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | 'admin:beta-users'
      | 'admin:dashboard'
      | 'admin:publication:index'
      | 'admin:user:id'
      | 'admin:users'
      | 'user_details'
      | 'user_details:submissions'
    >,
    'admin:dashboard': RouteRecordInfo<
      'admin:dashboard',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin:beta-users': RouteRecordInfo<
      'admin:beta-users',
      '/admin/beta-users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin:publication:index': RouteRecordInfo<
      'admin:publication:index',
      '/admin/publications',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'admin:user:id': RouteRecordInfo<
      'admin:user:id',
      '/admin/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'user_details'
      | 'user_details:submissions'
    >,
    'user_details': RouteRecordInfo<
      'user_details',
      '/admin/user/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'user_details:submissions': RouteRecordInfo<
      'user_details:submissions',
      '/admin/user/:id/submissions',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'admin:users': RouteRecordInfo<
      'admin:users',
      '/admin/users',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/account.vue': {
      routes:
        | 'account'
        | 'account:labs'
        | 'account:labs:record-of-review'
        | 'account:profile'
        | 'account:record_of_review'
        | 'account:settings'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/account/labs.vue': {
      routes:
        | 'account:labs'
        | 'account:labs:record-of-review'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/account/labs/record-of-review.vue': {
      routes:
        | 'account:labs:record-of-review'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/account/profile.vue': {
      routes:
        | 'account:profile'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/account/record-of-review.vue': {
      routes:
        | 'account:record_of_review'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/account/settings.vue': {
      routes:
        | 'account:settings'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin.vue': {
      routes:
        | '/admin'
        | 'admin:beta-users'
        | 'admin:dashboard'
        | 'admin:publication:index'
        | 'admin:user:id'
        | 'admin:users'
        | 'user_details'
        | 'user_details:submissions'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/routes/admin/index.vue': {
      routes:
        | 'admin:dashboard'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin/beta-users.vue': {
      routes:
        | 'admin:beta-users'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin/publications.vue': {
      routes:
        | 'admin:publication:index'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin/user/[id].vue': {
      routes:
        | 'admin:user:id'
        | 'user_details'
        | 'user_details:submissions'
      views:
        | 'default'
      pathParamNames:
        | 'id'
    }
    'src/routes/admin/user/[id]/index.vue': {
      routes:
        | 'user_details'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin/user/[id]/submissions.vue': {
      routes:
        | 'user_details:submissions'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/routes/admin/users.vue': {
      routes:
        | 'admin:users'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
