/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/manage/publication': RouteRecordInfo<
      '/manage/publication',
      '/manage/publication',
      Record<never, never>,
      Record<never, never>,
      | '/manage/publication/[id]/'
      | '/manage/publication/[id]/(tabs)'
      | 'manage:publication:dashboard'
      | 'manage:publication:id'
      | 'manage:publication:invited'
      | 'manage:publication:submitters'
      | 'manage:publication:team'
      | 'manage:publication:user'
    >,
    'manage:publication:id': RouteRecordInfo<
      'manage:publication:id',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/manage/publication/[id]/'
      | '/manage/publication/[id]/(tabs)'
      | 'manage:publication:dashboard'
      | 'manage:publication:invited'
      | 'manage:publication:submitters'
      | 'manage:publication:team'
      | 'manage:publication:user'
    >,
    '/manage/publication/[id]/(tabs)': RouteRecordInfo<
      '/manage/publication/[id]/(tabs)',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | 'manage:publication:invited'
      | 'manage:publication:submitters'
      | 'manage:publication:team'
    >,
    'manage:publication:invited': RouteRecordInfo<
      'manage:publication:invited',
      '/manage/publication/:id/invited',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:submitters': RouteRecordInfo<
      'manage:publication:submitters',
      '/manage/publication/:id/submitters',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:team': RouteRecordInfo<
      'manage:publication:team',
      '/manage/publication/:id/team',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/manage/publication/[id]/': RouteRecordInfo<
      '/manage/publication/[id]/',
      '/manage/publication/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:dashboard': RouteRecordInfo<
      'manage:publication:dashboard',
      '/manage/publication/:id/dashboard',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'manage:publication:user': RouteRecordInfo<
      'manage:publication:user',
      '/manage/publication/:id/users/:userId',
      { id: ParamValue<true>, userId: ParamValue<true> },
      { id: ParamValue<false>, userId: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/routes/manage/publication.vue': {
      routes:
        | '/manage/publication'
        | '/manage/publication/[id]/'
        | '/manage/publication/[id]/(tabs)'
        | 'manage:publication:dashboard'
        | 'manage:publication:id'
        | 'manage:publication:invited'
        | 'manage:publication:submitters'
        | 'manage:publication:team'
        | 'manage:publication:user'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id].vue': {
      routes:
        | '/manage/publication/[id]/'
        | '/manage/publication/[id]/(tabs)'
        | 'manage:publication:dashboard'
        | 'manage:publication:id'
        | 'manage:publication:invited'
        | 'manage:publication:submitters'
        | 'manage:publication:team'
        | 'manage:publication:user'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id]/(tabs).vue': {
      routes:
        | '/manage/publication/[id]/(tabs)'
        | 'manage:publication:invited'
        | 'manage:publication:submitters'
        | 'manage:publication:team'
      views:
        | 'default'
    }
    'src/routes/manage/publication/[id]/(tabs)/invited.vue': {
      routes:
        | 'manage:publication:invited'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/(tabs)/submitters.vue': {
      routes:
        | 'manage:publication:submitters'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/(tabs)/team.vue': {
      routes:
        | 'manage:publication:team'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/index.vue': {
      routes:
        | '/manage/publication/[id]/'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/dashboard.vue': {
      routes:
        | 'manage:publication:dashboard'
      views:
        | never
    }
    'src/routes/manage/publication/[id]/users/[userId].vue': {
      routes:
        | 'manage:publication:user'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
