majestic:
  description: Create container to proxy Majestic Jest UI.
  template:
    services:
      majestic:
        type: node:14
        build:
          - cd client && yarn
        port: 4000
        command: "cd client && yarn test:unit:ui"
        scanner: false
    proxy:
      majestic:
        - majestic.ccr.lndo.site:4000
cypress:
  description: Install the cypress test runner and tooling command.
  template:
    services:
      cypress:
        type: node:14
        overrides:
          image: "cypress/included:6.3.0"
          environment:
            - DISPLAY
    tooling:
      cypress:
        service: cypress
        dir: /app/client
        cmd: cypress
mailhog:
  description: Catch mail output from CCR with mailhog.
  template:
    services:
      mailhog:
        type: mailhog:v1.0.0
        hogfrom:
          - appserver
    proxy:
      mailhog:
        - mailhog.ccr.lndo.site
