{{- if .Values.ingress.enabled -}}
{{- $fullName := include "pilcrow.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "pilcrow.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
  {{- if .Values.ingress.hostname }}
    - host: {{ tpl .Values.ingress.hostname $ | quote}}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "pilcrow.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
  {{- end }}

  {{- if and .Values.ingress.tls (or (include "common.ingress.certManagerRequest" ( dict "annotations" .Values.ingress.annotations )) .Values.ingress.selfSigned) }}
  tls:
    - hosts:
        - {{ tpl .Values.ingress.hostname $ | quote }}
      secretName: {{ printf "%s-tls" (tpl .Values.ingress.hostname $) }}
  {{- end }}

{{- end }}
