name: Build
description: "Builds the Docker images for Pilcrow"
inputs:
  target:
    description: "package to build"
    required: false
    default: "ci"
  token:
    description: "GitHub token to use for authentication"
  push:
    description: "Push the built images to the registry"
    required: false
    default: "true"
outputs:
  version:
    description: "Version of the package that was built"
    value: ${{ steps.parse-build-output.outputs.version }}
  tags:
    description: "List of tags"
    value: ${{ steps.docker-input-metadata.outputs.tags}}
  frontend-bundle:
    description: "Path to the frontend bundle"
    value: ${{ steps.parse-build-output.outputs.frontend-bundle }}
runs:
  using: "composite"
  steps:
    - uses: mesh-research/github-actions/pilcrow-toolkit@main
      id: setup
      with:
        target: ${{ inputs.target }}
        command: setup
    - uses: docker/setup-buildx-action@v3
      id: buildx
    - uses: oras-project/setup-oras@v1.2.3
    # - name: Cache
    #   uses: actions/cache@v3
    #   id: docker-yarn-cache
    #   with:
    #     path: |
    #       ${RUNNER_TEMP}/yarn-cache
    #     key: cache-yarn-${{ hashFiles('client/package.json', 'client/yarn.lock') }}
    #     restore-keys: |
    #       cache-yarn-
    # - name: inject cache into docker
    #   uses: reproducible-containers/buildkit-cache-dance@v3.1.0
    #   with:
    #     cache-map: |
    #       {
    #         "${RUNNER_TEMP}/yarn-cache": "/usr/local/share/.cache/yarn/v6"
    #       }
    #     skip-extraction: ${{ steps.docker-yarn-cache.outputs.cache-hit }}
    - name: Docker Meta
      id: docker-input-metadata
      uses: docker/metadata-action@v5
      with:
        images: ${{ steps.setup.outputs.image-template }}
        tags: |
          type=edge
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
    - uses: int128/docker-build-cache-config-action@v1
      id: docker-registry-cache
      with:
        image: ${{ steps.setup.outputs.docker-registry-cache }}
        pull-request-cache: true
    - name: Prepare Build
      uses: mesh-research/github-actions/pilcrow-toolkit@main
      with:
        command: pre-build
        bake-files: |
          ./docker-bake.hcl
          ${{ steps.docker-input-metadata.outputs.bake-file }}
          ${{ steps.docker-registry-cache.outputs.bake-file }}
    - name: Execute Docker Bake
      id: docker-bake
      uses: docker/bake-action@v6.8.0
      env:
        BUILDSTAMP: ${{ steps.setup.outputs.buildstamp }}
        VERSION: ${{ steps.setup.outputs.version }}
        VERSION_URL: ${{ steps.setup.outputs.version-url }}
        VERSION_DATE: ${{ steps.setup.outputs.version-date }}
      with:
        push: ${{ inputs.push }}
        source: .
        targets: ${{ inputs.target }}
        allow: fs.write=*
        files: |
          ./docker-bake.hcl
          ${{ steps.docker-input-metadata.outputs.bake-file }}
          ${{ steps.docker-registry-cache.outputs.bake-file }}
    - name: Parse Docker Metadata Output
      id: parse-build-output
      uses: mesh-research/github-actions/pilcrow-toolkit@main
      with:
        command: parse-build-output
        docker-metadata: ${{ steps.docker-bake.outputs.metadata }}
