name: Build
description: "Builds the Docker images for Pilcrow"
inputs:
  target:
    description: "package to build"
    required: false
    default: "ci"
  token:
    description: "GitHub token to use for authentication"
outputs:
  version:
    description: "Version of the package that was built"
    value: ${{ steps.docker-meta.outputs.version }}
  tags:
    description: "List of tags"
    value: ${{ steps.docker-meta.outputs.tags}}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set Environment Variables
      id: tagger
      shell: bash
      run: |
        VERSION=$(git describe --tags)
        VERSION_URL=https://github.com/MESH-Research/Pilcrow/commits/${GITHUB_SHA}
        VERSION_DATE=$(git show -s --format=%cI ${GITHUB_SHA})
        REPO=${GITHUB_REPOSITORY,,}
        DOCKER_IMAGE_CACHE=ghcr.io/${REPO}/cache/__service__
        echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
        echo "VERSION_URL=${VERSION_URL}" >> "$GITHUB_ENV"
        echo "VERSION_DATE=${VERSION_DATE}" >> "$GITHUB_ENV"
        echo "REPO=${REPO}" >> "$GITHUB_ENV"
        echo "DOCKER_IMAGE_CACHE=${DOCKER_IMAGE_CACHE}" >> "$GITHUB_ENV"
        if [ "${{ inputs.target }}" == "release" ]; then
            echo "IMAGE_BASE=ghcr.io/${REPO}/__service__" >> "$GITHUB_ENV"
        else
            echo "IMAGE_BASE=${DOCKER_IMAGE_CACHE}" >> "$GITHUB_ENV"
        fi
    - name: Replace version in source files
      shell: bash
      run: |
        echo "::group::Replace version strings in source"
        sed -i "s|env('VERSION', '')|env('VERSION', '${VERSION}')|" backend/config/app.php
        sed -i "s|env('VERSION_URL', '')|env('VERSION_URL', '${VERSION_URL}')|" backend/config/app.php
        sed -i "s|env('VERSION_DATE', '')|env('VERSION_DATE', '${VERSION_DATE}')|" backend/config/app.php
        sed -i "s|process.env.VERSION_DATE|'${VERSION_DATE}'|" client/src/components/AppFooter.vue
        sed -i "s|process.env.VERSION_URL|'${VERSION_URL}'|" client/src/components/AppFooter.vue
        sed -i "s|process.env.VERSION|'${VERSION}'|" client/src/components/AppFooter.vue
        echo "::endgroup::"
    - uses: docker/setup-buildx-action@v3
    - name: Docker Meta
      id: docker-meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.IMAGE_BASE }}
        tags: |
          type=edge
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha,enable=${{ inputs.target == 'default'}}
    - uses: int128/docker-build-cache-config-action@v1
      id: docker-cache
      with:
        image: ${{ env.DOCKER_IMAGE_CACHE }}
    - name: Upload Docker Bake Files
      uses: actions/upload-artifact@v4
      with:
        name: docker-cache-bake-file
        path: |
          ${{ steps.docker-cache.outputs.bake-file }}
          ${{ steps.docker-meta.outputs.bake-file }}
          ./docker-bake.hcl
    - name: Build and push
      id: docker-bake
      uses: docker/bake-action@v6.8.0
      if: ${{ steps.docker-meta.outputs.tags != ''}}
      with:
        source: .
        targets: ${{ inputs.target }}
        allow: fs.write=*
        files: |
          ./docker-bake.hcl
          ${{ steps.docker-meta.outputs.bake-file }}
          ${{ steps.docker-cache.outputs.bake-file }}

    - name: tgz Frontend Assets
      if: ${{ steps.docker-meta.outputs.tags != ''}}
      shell: bash
      run: |
        echo "::group::Compress frontend assets"
        tar -czvf frontend-bundle.tar.gz \
          -C /tmp/webbuild/var/www/html .
        echo "::endgroup::"
    - name: Upload Frontend Assets
      if: ${{ steps.docker-meta.outputs.tags != ''}}
      uses: actions/upload-artifact@v4
      with:
        name: frontend-bundle
        path: /tmp/webbuild/var/www/html/
    - name: Publish Frontend Bundle
      if: ${{ steps.docker-meta.outputs.tags != ''}}
      uses: oras-project/setup-oras@v1
    - shell: bash
      if: ${{ steps.docker-meta.outputs.tags != ''}}
      env:
        OWNER: ${{ github.repository_owner }}
        METADATA: ${{ steps.docker-bake.outputs.metadata }}
      run: |
        echo ${{ inputs.token }} | oras login --username wreality --password-stdin ghcr.io
        image="$(echo $METADATA | jq -r 'to_entries[] | select(.key|endswith("web")).value."image.name"')"
        image="${image%,*}"
        oras attach $image \
          --artifact-type application/vnd.mesh.frontend-bundle.v1+tar \
          frontend-bundle.tar.gz
