name: Build
inputs:
    target:
        description: "package to build"
        required: false
outputs:
    version:
        description: "Version of the package that was built"
        value: ${{ steps.version.outputs.version }}
runs:
    using: "composite"
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Find Tag
          id: tagger
          shell: bash
          run: |
              git fetch --prune --unshallow
              echo "VERSION=$(git describe --tags)" >> ${GITHUB_ENV}
              echo "VERSION_URL=https://github.com/MESH-Research/Pilcrow/commits/${GITHUB_SHA}" >> ${GITHUB_ENV}
              echo "VERSION_DATE=$(git show -s --format=%cI ${GITHUB_SHA})" >> ${GITHUB_ENV}
        - uses: docker/setup-buildx-action@v3
        - name: Docker meta (FPM)
          id: docker-meta-fpm
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/${{ github.repository }}/fpm
            tags: |
              type=ref,event=pr,enable=${{ inputs.target == 'release' }}
              type=edge,enable=${{ inputs.target == 'release' }}
              type=semver,pattern={{version}},enable=${{ inputs.target == 'release' }}
              type=semver,pattern={{major}}.{{minor}},enable=${{ inputs.target == 'release' }}
              type=sha
            bake-target: fpm
        - name: Docker meta (WEB)
          id: docker-meta-web
          uses: docker/metadata-action@v4
          with:
            images: |
              ghcr.io/${{ github.repository }}/web
            tags: |
              type=ref,event=pr,enable=${{ inputs.target == 'release' }}
              type=edge,enable=${{ inputs.target == 'release' }}
              type=semver,pattern={{version}},enable=${{ inputs.target == 'release' }}
              type=semver,pattern={{major}}.{{minor}},enable=${{ inputs.target == 'release' }}
              type=sha
            bake-target: web
        - name: Build and push
          uses: docker/bake-action@v4
          with:
            targets: ${{ inputs.target }}
            files: |
              ./docker-bake.hcl
              ${{ steps.docker-meta-fpm.outputs.bake-file }}
              ${{ steps.docker-meta-web.outputs.bake-file }}
        - name: Write version
          id: version
          run: |
              echo "version=${{ steps.docker-meta-fpm.outputs.version }}" >> "$GITHUB_OUTPUT"