kind: Secret
apiVersion: v1
metadata:
  name: {{ include "pilcrow.secrets.defaultName" . }}
  labels:
    {{- include "pilcrow.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  {{ include "pilcrow.secrets.generate" (list "APP_KEY" .Values.pilcrow.appKey $ | default (randAlphaNum 32) ) }}
  {{ if not .Values.mysql.enabled }}
  {{ include "pilcrow.secrets.generate" (list "DB_PASSWORD" .Values.pilcrow.mysql.password $) }}
  {{ end }}
  {{ if not .Values.redis.enabled }}
  {{ include "pilcrow.secrets.generate" (list "REDIS_PASSWORD" .Values.pilcrow.redis.password $) }}
  {{ end }}
  {{- if (eq .Values.pilcrow.mail.driver "smtp") -}}
  {{ include "pilcrow.secrets.generate" (list "MAIL_PASSWORD" .Values.pilcrow.mail.smtp.password $) }}
  {{- else if (eq .Values.pilcrow.mail.driver "ses") -}}
  {{ include "pilcrow.secrets.generate" (list "AWS_SECRET_ACCESS_KEY" .Values.pilcrow.mail.ses.secretAccessKey $) }}
  {{- end -}}
