name: "Start Testing Stack"
description: "Start the default testing stack."
runs:
    using: "composite"
    steps:
        - uses: actions/checkout@v3
        - uses: ./.github/actions/load-image
        - run: |
              cp backend/.env.example .env
              cp docker-compose.ci.yaml docker-compose.override.yaml
              docker compose up -d
              docker compose exec -T phpfpm composer install
              docker compose exec -T phpfpm bash -c "/wait && ./artisan migrate:fresh --seed"
          shell: bash
