kind: Job
apiVersion: batch/v1
metadata:
  name: {{ include "pilcrow.fullname" . }}-mysql-migrate
  labels:
    {{- include "pilcrow.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
spec:
  template:
    metadata:
      labels:
        {{- include "pilcrow.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "pilcrow.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mysql-migrate
          image: "{{ .Values.image.fpmRepository }}:{{- .Values.image.tag | default .Chart.AppVersion -}}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- include "pilcrow.fpmEnv" . | nindent 10 }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              php artisan migrate --force;
          resources:
            {{- toYaml .Values.fpm.resources | nindent 12 }}
      restartPolicy: OnFailure
