kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "pilcrow.fullname" . }}-files
  labels:
    {{- include "pilcrow.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/*").AsConfig | indent 2 }}
