---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: "Style"

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches: [development, master]
  pull_request:

###############
# Set the Job #
###############
jobs:
  all:
    # Name the Job
    name: Lint/Style Checking
    # Set the agent to run on
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Cache Composer packages
        id: composer-cache-root
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Cache Root Node packages
        id: yarn-root-cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Cache Client Node packages
        id: yarn-client-cache
        uses: actions/cache@v2
        with:
          path: client/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn install
          composer install
          cd client && yarn install
      - name: Check markdown
        run: yarn lint:md
      - name: Check PHP
        run: composer lint
      - name: Check Javascript
        run: cd client && yarn lint
