name: Publish Helm Chart
on:
  push:
    tags:
      - "pilcrow-helm-v*"
permissions:
  packages: write
concurrency:
  group: helmpub-${{ format('{0}-{1}', github.ref_name || github.run_number, github.job) }}
  cancel-in-progress: true
jobs:
  publish:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - run: echo "REPO=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - uses: wreality/helm-push@v1.1.1
        id: helm-push
        with:
          useOCIRegistry: true
          registry-url: oci://ghcr.io/${{ env.REPO }}
          username: ${{ github.actor }}
          access-token: ${{ secrets.REPO_TOKEN }}
          update-dependencies: true
          chart-folder: helm
      - name: Attach helm chart to release
        run: |
          gh release upload ${{ github.ref_name }} ${{ github.workspace }}/${{ steps.helm-push.outputs.chart-package }}
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
